/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0bc709d7dec048dc99e2b99ee805dc43)
interface __BaseEnv_Env {
	MEDIOS: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
